networks: 
  auth-network:
    driver: bridge
        
services:
  backend:
    container_name: auth_api
    restart: always
    env_file: .env
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
    - auth-network
    # environment:
    #   WAIT_HOSTS: database:${DB_PORT}
    #   WAIT_TIMEOUT: 600
    #   WAIT_SLEEP_INTERVAL: 10
    command: >
      sh -c "yarn dev"
    volumes:
      - ./:/usr/src
      - ./node_modules:/usr/src/node_modules

  database:
    container_name: auth_database
    image: postgres
    restart: always
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DATABASE: ${DB_DATABASE}
    networks:
    - auth-network
    command: -p ${DB_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 